language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: e01e472fc77b763ed4ed946dd25a58133bfb2880
 local_dir: dist
 on:
   branch: master